export const fonts = {
    poppins_regular: "Poppins-Regular",
    poppins_medium: "Poppins-Medium",
    poppins_semi_bold: "Poppins-SemiBold",
    poppins_bold: "Poppins-Bold",
  };

  export const BikeServices = [
    { name: "Towing", id: 1, service: "2W" },
    { name: "Fuel Delivery", id: 2, service: "2W" },
    { name: "Flat Tyre", id: 3, service: "2W" },
    { name: "Key Lockout", id: 4, service: "2W" },
    { name: "Tyre Changing", id: 5, service: "2W" },
    { name: "Engine Oil Replacement", id: 6, service: "2W" },
    { name: "Light Fitting", id: 7, service: "2W" },
    { name: "Fog Lamp", id: 8, service: "2W" },
    { name: "Starting Problem", id: 9, service: "2W" },
    { name: "Battery Change", id: 10, service: "2W" },
    { name: "Air Filter Cleaning", id: 11, service: "2W" },
    { name: "Break Shoe/Pad Roughing", id: 12, service: "2W" },
    { name: "Break Drum Cleaning & Adjustment", id: 13, service: "2W" },
    { name: "Chain Lubrication", id: 14, service: "2W" },
    { name: "Spark Plug Cleaning/Replacement", id: 15, service: "2W" },
    { name: "All Cable Lubrication", id: 16, service: "2W" },
    { name: "Disc Brake Oil Check/Top-Up", id: 17, service: "2W" },
    { name: "Mirror Adjustment", id: 18, service: "2W" },
    { name: "Carburetor Cleaning", id: 19, service: "2W" },
    { name: "Minor Electrical Checking", id: 20, service: "2W" },
    { name: "Self Motor Checking", id: 21, service: "2W" },
    { name: "All Minor (Nut & Bolt Tight)", id: 22, service: "2W" },
    { name: "Vehicle Wash", id: 23, service: "2W" },
  ];
  
  export const AutoServices = [
    { name: "Towing", id: 23, service: "3W" },
    { name: "Fuel Delivery", id: 24, service: "3W" },
    { name: "Flat Tyre", id: 25, service: "3W" },
    { name: "Key Lockout", id: 26, service: "3W" },
    { name: "Tyre Changing", id: 27, service: "3W" },
    { name: "Wiper Fitment", id: 28, service: "3W" },
    { name: "Battery Jump Start", id: 29, service: "3W" },
    { name: "Lubricant Change", id: 30, service: "3W" },
    { name: "Light Fitting", id: 31, service: "3W" },
    { name: "Fog Lamp", id: 32, service: "3W" },
    { name: "Starting Problem", id: 33, service: "3W" },
    { name: "Battery Change", id: 34, service: "3W" },
    { name: "Air Filter Cleaning", id: 35, service: "3W" },
    { name: "Break Shoe/Pad Roughing", id: 36, service: "3W" },
    { name: "Break Drum Cleaning & Adjustment", id: 37, service: "3W" },
    { name: "All Cable Lubrication", id: 38, service: "3W" },
    { name: "Mirror Adjustment", id: 39, service: "3W" },
    { name: "Minor Electrical Checking", id: 40, service: "3W" },
    { name: "Self Motor Checking", id: 41, service: "3W" },
    { name: "All Minor (Nut & Bolt Tight)", id: 42, service: "3W" },
    { name: "Oil Filter Replacement", id: 43, service: "3W" },
    { name: "Fuel Filter Change", id: 44, service: "3W" },
    { name: "Vehicle Wash", id: 45, service: "3W" },
  ];
  
  export const CarServices = [
    { name: "Towing", id: 45, service: "4W" },
    { name: "Fuel Delivery", id: 46, service: "4W" },
    { name: "Flat Tyre", id: 47, service: "4W" },
    { name: "Key Lockout", id: 48, service: "4W" },
    { name: "Tyre Changing", id: 49, service: "4W" },
    { name: "Wiper Fitment", id: 50, service: "4W" },
    { name: "GPS Rectification", id: 51, service: "4W" },
    { name: "Front & Rear Dash-Cam", id: 52, service: "4W" },
    { name: "Battery Jump Start", id: 53, service: "4W" },
    { name: "Lubricant Change", id: 54, service: "4W" },
    { name: "Light Fitting", id: 55, service: "4W" },
    { name: "Fog Lamp", id: 56, service: "4W" },
    { name: "Starting Problem", id: 57, service: "4W" },
    { name: "Battery Change", id: 58, service: "4W" },
    { name: "Air Filter Cleaning", id: 59, service: "4W" },
    { name: "Break Shoe/Pad Roughing", id: 60, service: "4W" },
    { name: "Break Drum Cleaning & Adjustment", id: 61, service: "4W" },
    { name: "All Cable Lubrication", id: 62, service: "4W" },
    { name: "Mirror Adjustment", id: 63, service: "4W" },
    { name: "Minor Electrical Checking", id: 64, service: "4W" },
    { name: "Self Motor Checking", id: 65, service: "4W" },
    { name: "All Minor (Nut & Bolt Tight)", id: 66, service: "4W" },
    { name: "Oil Filter Replacement", id: 67, service: "4W" },
    { name: "Fuel Filter Change", id: 68, service: "4W" },
    { name: "Coolant Top-Up", id: 69, service: "4W" },
    { name: "Vehicle Wash", id: 70, service: "4W" },
    { name: "Driver on Call", id: 71, service: "4W" },
  ];
  